### ISSUE TITLE
Anime: More notification options

### ISSUE THREAD

**Issue by RequiDev** [animenotifier/notify.moe#206] opened 2018-12-24 22:30 UTC
I don't always see the notifications and sometimes they don't appear on my phone either. An option to receive notifications by mail or a Telegram Bot would be awesome.

**Comment by akyoto** [comment] 2018-12-25 08:25
Regarding "they don't appear on my phone", I'm wondering what the problem is.

* Did you enable [instant notifications](https://notify.moe/settings/notifications) on all devices? (it's a per-device / per-browser setting)
* Is the "Send test notification" button working? If you click it on a desktop PC, does your phone receive it? (enable instant notifications on both)

**Comment by akyoto** [comment] 2018-12-25 08:30
May I mark this as a duplicate of #45 and close it in favor of the existing one?

**Comment by RequiDev** [comment] 2018-12-25 08:55
I have instant notifications enabled on both my pc and my phone. Test notifications work fine and appear on both devices.

The referenced issue seems to be a year old. At least I've brought it up again, I guess.

**Comment by akyoto** [comment] 2018-12-25 10:54
Yea, it's not forgotten. I'm grouping issues into priorities on the [project page](https://github.com/animenotifier/notify.moe/projects/10). The code actually exists already in the arn repository but it's not in use yet (need to register at a mailing service).

Thanks for taking the time to bring it up again 👍

**Closed as completed** 2018-12-25 10:55 UTC
