### ISSUE TITLE
User: Custom Lists

### ISSUE THREAD

**Issue by ghost** [animenotifier/notify.moe#218] opened 2019-03-07 11:38 UTC
Give the user the ability to add a custom list similar to AniList to make it easier for users to group anime

**Comment by Robjack19** [comment] 2019-03-07 11:45
![bow](https://user-images.githubusercontent.com/46964493/53954548-8ba08580-40fc-11e9-82bc-6aadaa560b38.gif)

**Comment by Robjack19** [comment] 2019-03-07 11:48
<div class="tenor-gif-embed" data-postid="7280930" data-share-method="host" data-width="100%" data-aspect-ratio="1.7857142857142858"><a href="https://tenor.com/view/anime-sorry-moe-bow-gif-7280930">Anime Sorry GIF</a> from <a href="https://tenor.com/search/anime-gifs">Anime GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by akyoto** [comment] 2019-03-09 03:39
Duplicate of #40

**Closed as completed by akyoto** 2019-03-09 03:39 UTC
